export const REQUESTED = "REQUESTED";
export const FAILURE = "FAILURE";

export const ELECTRONIC_SUCCESS = "SUCCESS";

export const GLASS_SUCCESS = "GLASS_SUCCESS";

export const JEWELLERY_SUCCESS = "JEWELLERY_SUCCESS";

export const DECORATION_SUCCESS = "DECORATION_SUCCESS";

export const AUTOMOBILES_SUCCESS = "AUTOMOBILES_SUCCESS"
