export const GET_PRODUCTS_REQUEST='GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE='GET_PRODUCTS_FAILURE';

export const GET_CAROSELS_DATA_REQUEST = "GET_CAROSELS_DATA_REQUEST";
export const GET_CAROSELS_DATA_SUCCESS = "GET_CAROSELS_DATA_SUCCESS";
export const GET_CAROSELS_DATA_FAILURE = "GET_CAROSELS_DATA_FAILURE";

