export const PRODUCT_GET_CART_SUCESS = "PRODUCT_GET_CART_SUCESS";

export const PRODUCT_ADD_CART_REQUEST = 'PRODUCT_ADD_CART_REQUEST';
export const PRODUCT_ADD_CART_SUCCESS = 'PRODUCT_ADD_CART_SUCCESS';
export const PRODUCT_ADD_CART_FAILURE = 'PRODUCT_ADD_CART_FAILURE';

export const PRODUCT_DELETE_CART_REQUEST = 'PRODUCT_DELETE_CART_REQUEST';
export const PRODUCT_DELETE_CART_SUCCESS = 'PRODUCT_DELETE_CART_SUCCESS';
export const PRODUCT_DELETE_CART_FAILURE = 'PRODUCT_DELETE_CART_FAILURE';

export const PRODUCT_ORDER_PLACED_SUCCESS = 'PRODUCT_ORDER_PLACED_SUCCESS';